using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CK.SqlServer
{
    public class SqlIdentifiers
    {
        string[] _keywords = new string[] 
        {
      "if",
      "else",
      "begin",
      "break",
      "end",
      "case",
      "when",
      "default",
      "label",
      "goto",
      "is",
      "null",
      "return",
      "while",

      "as",
      "alter",
      "close",
      "collate",
      "commit",
      "continue",
      "create",
      "database",
      "function",
      "index",
      "procedure",
      "rule",
      "schema",
      "statistics",
      "table",
      "trigger",
      "view",
      "cursor",
      "deallocate",
      "declare",
      "cursor",
      "delete",
      "deny",
      "drop",
      "dump",
      "execute",
      "fetch",
      "from",
      "grant",
      "having",
      "identity",
      "kill",
      "load",
      "open",
      "order",
      "by",
      "print",
      "raiserror",
      "reconfigure",
      "restore",
      "filelistonly",
      "headeronly",
      "labelonly",
      "verifyonly",
      "reverse",
      "revoke",
      "right",
      "rollback",
      "transaction",
      "work",
      "round",
      "rowcount_big",
      "save",
      "select",
      "set",
      "shutdown",

      "float",
      "real",
      "int", 
      "bigint",
      "smallint",
      "tinyint",
      "datetime",
      "datetime2",
      "smalldatetime",
      "smallint",
      "smallmoney",
      "sql_variant",
      "text",
      "timestamp",
      "tinyint",
      "varbinary",
      "varchar",

      "union",
      "update",
      "updatetext",
      "use",
      "waitfor",
      "where",
    };

        public String[] Keywords { get { return _keywords; } }
    }
}
