using CK.Core;
using System;

namespace CK.Testing.StObjMap
{
    /// <summary>
    /// Gives access to one or more StObjMaps by loading them from existing generated assemblies.
    /// </summary>
    public interface IStObjMapTestHelperCore
    {
        /// <summary>
        /// Gets the generated assembly name from "StObjMap/GeneratedAssemblyName" configuration.
        /// Defaults to <see cref="Setup.StObjEngineConfiguration.DefaultGeneratedAssemblyName"/>.
        /// <para>
        /// This is updated each time <see cref="ResetStObjMap"/> is called with a ".Reset.#num" suffix
        /// (where #num is an incremented number starting at 1).
        /// </para>
        /// <para>
        /// The original name must not contain a ".Reset." part in its name otherwise an <see cref="ArgumentException"/> is thrown.
        /// </para>
        /// </summary>
        string GeneratedAssemblyName { get; }

        /// <summary>
        /// Gets the <see cref="IStObjMap"/> from the current <see cref="GeneratedAssemblyName"/>.
        /// The assembly, if it exists, is the one in the <see cref="IBasicTestHelper.BinFolder"/>.
        /// </summary>
        IStObjMap StObjMap { get; }

        /// <summary>
        /// Fires whenever the <see cref="StObjMap"/> is accessed.
        /// </summary>
        event EventHandler<StObjMapAccessedEventArgs> StObjMapAccessed;

        /// <summary>
        /// Resets the <see cref="StObjMap"/>: internally sets it to null and appends a ".Reset.#num" suffix
        /// (where #num is an incremented number starting at 1) to <see cref="GeneratedAssemblyName"/> so
        /// that a new dll must be generated by <see cref="StObjMapLoading"/>.
        /// </summary>
        /// <param name="deleteGeneratedBinFolderAssembly">
        /// By default, <see cref="DeleteGeneratedAssemblies(string)"/> is called on the <see cref="IBasicTestHelper.BinFolder"/>.
        /// </param>
        void ResetStObjMap( bool deleteGeneratedBinFolderAssembly = true );

        /// <summary>
        /// Fires the first time the <see cref="StObjMap"/> on current <see cref="GeneratedAssemblyName"/>
        /// must be loaded.
        /// </summary>
        event EventHandler StObjMapLoading;

        /// <summary>
        /// Deletes all files like <see cref="GeneratedAssemblyName"/> or GeneratedAssemblyName.Reset.#num
        /// in the specified directory.
        /// </summary>
        /// <param name="directory">The directory from which generated assembly(ies) must be deleted.</param>
        /// <returns>The number of deleted files.</returns>
        int DeleteGeneratedAssemblies( string directory );

        /// <summary>
        /// Loads a <see cref="IStObjMap"/> from existing generated assembly in the <see cref="IBasicTestHelper.BinFolder"/>.
        /// Actual loading of the assembly is done only if the StObjMap is not already available.
        /// </summary>
        /// <returns>The map or null if an error occurred (the error is logged).</returns>
        IStObjMap LoadStObjMap( string assemblyName, bool withWeakAssemblyResolver = true );

    }
}
