<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <IsPackable>False</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="**\*.sql;**\*.tql;**\*.y4" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Res\sVerbatimParameterProc.sql" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\CK.SqlServer.Setup.Model\CK.SqlServer.Setup.Model.csproj" />
    <PackageReference Include="CK.SqlServer.Transaction" Version="13.0.0--ci.2" />
  </ItemGroup>
</Project>